name: Android APK Build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Unzip project
        run: unzip atrat_lina_android_project.zip -d project

      - name: Make gradlew executable
        run: chmod +x project/gradlew

      - name: Build Debug APK
        working-directory: project
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AtratLina-debug-apk
          path: project/app/build/outputs/apk/debug/app-debug.apk
